config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'home#landing'
  end

  unauthenticated :user do
    root to: 'home#front'
  end

  resources :places, only: [:index, :show] do
    collection do
      get 'search'
    end
  end

  resources :posts, only: [:create, :show] do
    collection do
      get 'shared'
    end
  end

  resources :users do
    collection do
      get '/:username', to: 'users#profile', as: :profile
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  include PgSearch
  pg_search_scope :match_by_name, against: :name, using: { tsearch: { prefix: true } }

  validates :name, :lat, :long, presence: true

  def self.search_with_params(params)
    places = self.all
    places = places.where("places.name LIKE ?", "%#{params[:name]}%") if params[:name].present?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  attr_accessor :placename

  include PgSearch
  pg_search_scope :match_by_content, against: :content, using: { tsearch: { prefix: true } }

  validates :content, presence: true

  belongs_to :place
  belongs_to :user, counter_cache: true

  scope :public_posts, -> { where(public: true) }

  def self.search_with_params(params)
    posts = all
    posts = posts.where("':user_ids' = ANY (user_ids)", user_ids: params[:user_ids]) if params[:user_ids].present?
  end

  def can_be_viewed?(user)
    user_ids.include?(user.id) || user.posts.include?(self)
  end

  def is_private?
    public == false
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true
  validates :name, presence: true

  has_many :posts


  def self.search_with_params(params)
    users = self.all
    users = users.where.not(id: params[:all_users]) if params[:all_users].present?
  end

  def public_posts
    self.posts.where(public: true)
  end

  def viewable_posts(user)
    user.posts.search_with_params(user_ids: id) + user.public_posts
  end

  def feed_posts
    Post.includes(:place).search_with_params(user_ids: id) + posts.includes(:place)
  end
end

app/controllers/application_controller.rb
require 'will_paginate/array'

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end

  def render_404
    respond_to do |format|
      format.html { render file: "#{Rails.root}/public/404", layout: false, status: :not_found }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:landing]

  def landing
    @users = User.search_with_params(all_users: current_user.id).pluck(:name, :id).to_h
    @post = Post.new
    @posts = current_user.feed_posts.paginate(page: params[:page])
  end

  def front
    @post = Post.includes(:place).public_posts.last
    (gon.place = @post.place) if @post
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!

  def index
    @places = Place.paginate(page: params[:page])
  end

  def show
    @place = Place.find(params[:id])
    gon.place = @place
  end

  def search
    @places = Place.match_by_name(params[:name]).limit(5).pluck(:name)
    render json: @places
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :update_params, only: [:create]
  before_action :check_location, only: [:create]
  before_action :set_post, only: [:show]
  before_action :check_privacy, only: [:show]

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post), notice: 'Post save successfully!'
    else
      redirect_to root_path, alert: @post.errors
    end
  end

  def show
    gon.place = @post.place
  end

  def shared
    params[:user_ids] = current_user.id
    @posts = Post.search_with_params(params)
  end

  private

  def post_params
    params.require(:post).permit(:content, :place_id, :public, user_ids: [])
  end

  def check_location
    @place = Place.find_by(name: params[:post][:placename])
    if @place
      params[:post][:place_id] = @place.id
    else
      redirect_to places_path, alert: 'Please select one of these location.'
    end
  end

  def update_params
    params[:post][:user_ids] = params[:post][:user_ids].reject(&:empty?)
  end

  def set_post
    @post = Post.find(params[:id]) if params[:id]
  end

  def check_privacy
    if @post.is_private?
      render_404 && return unless @post.can_be_viewed?(current_user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_username, only: [:profile]

  def profile
    @users = User.search_with_params(all_users: current_user.id).pluck(:name, :id).to_h
    @post = Post.new
    if current_user.username == params[:username]
      @posts = current_user.posts.includes(:place).paginate(page: params[:page])
    else
      @posts = current_user.viewable_posts(@user).paginate(page: params[:page])
    end
  end

  private

  def check_username
    @user = User.find_by(username: params[:username])
    render_404 && return unless @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shared_helper.rb
module SharedHelper
  def post_privacy_icon(post)
    post.public ? 'globe' : 'lock'
  end

  def non_owner_class(post)
    'post_shared_with_you' if post.user != current_user
  end

  def post_privacy_tooltip(post)
    post.public ? 'Public post' : 'Private post'
  end
end

app/views/home/front.html.erb
<div class="row container">
  <div id="newsfeed" class="col-lg-6">
    <h4><%= fa_icon "newspaper-o" %>
      One of many Community's public post |
      <%= link_to 'Sign in', new_user_session_path %> or
      <%= link_to 'Sign up', new_user_registration_path %>
    </h4>
    <div id="activities">
      <div class="well">
        <% if @post %>
          <%= render 'shared/post_panel', post: @post %>
        <% else %>
          <p>No posts found!</p>
        <% end %>
      </div>
    </div>
  </div>
  <div id="intro" class="col-lg-6">
    <h1>QI Place Sharing</h1>
    <p>QI Place Sharing site is built on <%= fa_icon 'diamond' %> Ruby on Rails as part of QI's assignment.</p>
  </div>
</div>

app/views/home/landing.html.erb
<div class="row">
  <div class="col-lg-3">
    <%= render 'shared/user_info' %>
  </div>
  <div id="post_form" class="col-lg-6">
    <%= render 'shared/post_form' %>

    <%= render 'shared/activities', activities_text: 'Your Posts & Posts Shared with You!' %>

    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialLocator</title>
    <%= include_gon %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://openlayers.org/en/v4.2.0/css/ol.css" type="text/css">
  </head>

  <body>
    <script src="https://openlayers.org/en/v4.2.0/build/ol.js" type="text/javascript"></script>

    <% unless notice.blank? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
    <% end %>

    <% unless alert.blank? %>
      <div class="alert alert-danger">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
    <% end %>

    <%= render 'shared/navbar' %>
    <div id="yield-main" class="<%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
  </body>
</html>

app/views/places/_place.html.erb
<script src="https://openlayers.org/en/v4.2.0/build/ol.js" type="text/javascript"></script>

<div id="map" class="map"></div>
<script type="text/javascript">
var map = new ol.Map({
  target: 'map',
  layers: [
    new ol.layer.Tile({
      source: new ol.source.OSM()
    })
  ],
  view: new ol.View({
    center: ol.proj.fromLonLat([parseFloat('<%= place.lat %>'), parseFloat('<%= place.long %>')]),
    zoom: 4
  })
});
</script>

app/views/places/index.html.erb
<h1>All Places</h1>

<ul class="list-group">
  <% @places.each do |place| %>
    <li class="list-group-item">
      <%= place.name %> |
      <%= link_to 'View', place_path(place) %>
    </li>
  <% end %>
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</ul>

app/views/places/show.html.erb
<h2><%= @place.name %></h2>

<div class="well">
  <div id="map" style="width: 60%, height: 50px"></div>
</div>

app/views/posts/shared.html.erb
<div class="container">
  <h3><%= fa_icon 'share-alt' %> Posts shared with you.</h3>

  <% @posts.each do |post| %>
    <!-- TODO: refactor to partial -->
    <div class="well">
      <%= fa_icon 'user-circle' %>
      <b><%= current_user.name %></b> says "<%= post.content %>" about "<%= post.place.name %>".
      <%= link_to 'Click to view', post_path(post) %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="panel panel-default post_panel">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= fa_icon 'user-circle' %>
      <b><%= @post.user.name %> says</b>:
      <span class="text-primary"><%= @post.content %></span>
      <span class="post_share_state pull-right" data-toggle="tooltip" title="<%= post_privacy_tooltip(@post) %>">
        <%= fa_icon post_privacy_icon(@post) %>
      </span>
    </h3>
  </div>
  <div class="panel-body">
    <div id="place_show_map" class="place_show_map"></div>
  </div>
  <div class="panel-footer">
    <%= fa_icon 'share-square-o' %>
    <%= current_user.name %> shared this on
    <span class="text-info">
      <b><%= @post.created_at.to_formatted_s(:long_ordinal) %></b>
    </span>
  </div>
</div>

app/views/shared/_activities.html.erb
<div id="activities">
  <% unless @posts.empty? %>
    <h4><%= fa_icon "newspaper-o" %> <%= activities_text %></h4>
    <% @posts.each do |post| %>
      <div class="well  <%= non_owner_class(post) %>">
        <%= fa_icon 'user-circle' %>
        <b><%= post.user.name %></b> says "<%= post.content %>" about "<%= post.place.name %>".
        <%= link_to 'Click to view', post_path(post) %>

        <span class="post_share_state pull-right">
          <%= fa_icon(post_privacy_icon(post)) %>
        </span>

      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_card.html.erb
<ul class="list-group">
  <% @users.each do |user| %>
    <li class="list-group-item">
      <%= user.name %> |
      <%= link_to 'Add friend', friendships_path(friend_id: user.id), method: :post %>
    </li>
  <% end %>
</ul>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-top">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Social Location Sharing", root_url, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-top">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to('Sign out', destroy_user_session_path, method: :delete) %></li>
        <% else %>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <li><%= link_to 'Sign in', user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_post_form.html.erb
<div class="well">
  <%= form_for @post, method: :post do |f| %>
  <div class="form-group">
    <h4>Share location with your friends</h4>
    <div class="form-group">
      <%= f.text_field :placename, class: 'form-control', placeholder: 'type & select location' %><br>
      <%= f.text_area :content, id: 'post_text', class: 'easy-autocomplete form-control', placeholder: 'Share your thoughts about the location.', rows: '5' %><br>
      <%= f.check_box :public, 'data-toggle': 'toggle', 'data-on': 'Public', 'data-off': 'Private', html: { checked: :checked } %><br><br>
      <div class="hidden_text">
        <%= f.select :user_ids, options_for_select(@users), {}, {multiple: true, class: 'form-control', include_blank: false, include_hidden: false} %><br><br>
      </div>
      <%= f.submit 'Share Location', class: 'btn btn-primary'%>
    </div>
    <% end %>
  </div>
  <br>
</div>

app/views/shared/_post_panel.html.erb
<div class="panel panel-default post_panel">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= fa_icon 'user-circle' %>
      <b><%= post.user.name %> says</b>:
      <span class="text-primary"><%= post.content %></span>

      <span class="post_share_state pull-right">
        <%= fa_icon(post_privacy_icon(post)) %>
      </span>

    </h3>
  </div>

  <div class="panel-body">
    <div id="front_page_map" class="front_page_map"></div>
  </div>

  <div class="panel-footer">
    <%= fa_icon 'share-square-o' %>
    <%= post.user.name %> shared this on
    <span class="text-info">
      <b><%= post.created_at.to_formatted_s(:long_ordinal) %></b>
    </span>
  </div>
</div>

app/views/shared/_user_info.html.erb
<div id="user-info" class="well">
  <div class="text-center">
    <%= link_to profile_users_path(current_user.username) do %>
      <%= image_tag 'avatar.png', class: 'avatar' %>
    <% end %>

    <h5><%= current_user.name %></h5>
  </div>
  <h5>
    <%= fa_icon 'shield' %>
    <%= pluralize(current_user.posts.count, 'post') %>
  </h5>
  <h5>
    <%= fa_icon 'envelope' %>
    <%= current_user.email %>
  </h5>
  <h5>
    <%= fa_icon 'share-alt' %>
    <%= link_to 'Posts shared with you', shared_posts_path %>
  </h5>
  <br>
</div>

app/views/users/profile.html.erb
<div class="row">
  <div class="col-lg-3">
    <%= render 'shared/user_info' %>
  </div>

  <div class="col-lg-6">
    <%= render 'shared/activities', activities_text: 'Your Posts' %>
    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  </div>
</div>